namespace JordiAragonZaragoza.Cinema.Reservation.User.Domain
{
    using System.Collections.Generic;
    using JordiAragonZaragoza.SharedKernel.Domain.Entities;

    public sealed class Assignment : BaseEntity<AssignmentId>
    {
        private readonly HashSet<Role> roles = new();

        internal Assignment(
            AssignmentId id, // TODO: The id is generated by the Scope, so it is not a Guid.
            Scope scope)
            : base(id)
        {
            this.Scope = scope;
        }

        // Required by EF.
        private Assignment()
        {
        }

        public Scope Scope { get; } = default!;

        public IReadOnlyCollection<Role> Roles
            => this.roles.AsReadOnly();

        internal void AddRole(Role role)
            => this.roles.Add(role);

        internal void RemoveRole(Role role)
            => this.roles.Remove(role);
    }
}