// <auto-generated />
using System;
using JordiAragon.Cinema.Reservation.Common.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JordiAragon.Cinema.Reservation.Common.Infrastructure.EntityFramework.Migrations.ReadModelStore
{
    [DbContext(typeof(ReservationReadModelContext))]
    partial class ReservationReadModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JordiAragon.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.AvailableSeatReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditoriumName")
                        .HasColumnType("text");

                    b.Property<short>("Row")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<short>("SeatNumber")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AvailableSeats");
                });

            modelBuilder.Entity("JordiAragon.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.ShowtimeReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditoriumName")
                        .HasColumnType("text");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("MovieRuntime")
                        .HasColumnType("interval");

                    b.Property<string>("MovieTitle")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SessionDateOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("JordiAragon.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.TicketReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditoriumName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTimeOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean");

                    b.Property<string>("MovieTitle")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SessionDateOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("JordiAragon.SharedKernel.Infrastructure.ProjectionCheckpoint.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckpointedAtOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Position")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("__Checkpoints", (string)null);
                });

            modelBuilder.Entity("JordiAragon.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.TicketReadModel", b =>
                {
                    b.OwnsMany("JordiAragon.Cinema.Reservation.Auditorium.Application.Contracts.ReadModels.SeatReadModel", "Seats", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Row")
                                .HasColumnType("smallint");

                            b1.Property<short>("SeatNumber")
                                .HasColumnType("smallint");

                            b1.HasKey("Id", "TicketId");

                            b1.HasIndex("TicketId");

                            b1.ToTable("TicketsSeats", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
