// <auto-generated />
using System;
using JordiAragonZaragoza.Cinema.Reservation.Common.Infrastructure.EntityFramework.Projections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JordiAragonZaragoza.Cinema.Reservation.Common.Infrastructure.EntityFramework.Projections.Migrations
{
    [DbContext(typeof(ReservationReadModelContext))]
    [Migration("20260629182104_InitialReadModelMigration")]
    partial class InitialReadModelMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Auditorium.Application.Contracts.ReadModels.AuditoriumReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auditoriums");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Cinema.Application.Contracts.ReadModels.CinemaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Movie.Application.Contracts.ReadModels.MovieReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Runtime")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Partition.Application.Contracts.ReadModels.PartitionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Partitions");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.AvailableSeatReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditoriumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AvailableSeats");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.ReservationReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditoriumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTimeOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SessionDateOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShowtimeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.ShowtimeReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditoriumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("MovieRuntime")
                        .HasColumnType("interval");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SessionDateOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Tenant.Application.Contracts.ReadModels.TenantReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.User.Application.Contracts.ReadModels.UserAuthorizationReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UsersAuthorizations_UserId");

                    b.HasIndex("UserId", "TenantId", "PartitionId", "DomainId")
                        .IsUnique()
                        .HasDatabaseName("IX_UsersAuthorizations_UserIdScope");

                    b.ToTable("UsersAuthorizations", (string)null);
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.User.Application.Contracts.ReadModels.UserReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JordiAragonZaragoza.SharedKernel.Infrastructure.ProjectionCheckpoint.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckpointedAtOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Position")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("__Checkpoints", (string)null);
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Auditorium.Application.Contracts.ReadModels.AuditoriumReadModel", b =>
                {
                    b.OwnsMany("JordiAragonZaragoza.Cinema.Reservation.Auditorium.Application.Contracts.ReadModels.SeatReadModel", "Seats", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AuditoriumId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Row")
                                .HasColumnType("integer");

                            b1.Property<int>("SeatNumber")
                                .HasColumnType("integer");

                            b1.HasKey("Id", "AuditoriumId");

                            b1.HasIndex("AuditoriumId");

                            b1.ToTable("AuditoriumSeats", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AuditoriumId");
                        });

                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("AuditoriumReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("AuditoriumReadModelId");

                            b1.ToTable("Auditoriums");

                            b1.WithOwner()
                                .HasForeignKey("AuditoriumReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Cinema.Application.Contracts.ReadModels.CinemaReadModel", b =>
                {
                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("CinemaReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("CinemaReadModelId");

                            b1.ToTable("Cinemas");

                            b1.WithOwner()
                                .HasForeignKey("CinemaReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Movie.Application.Contracts.ReadModels.MovieReadModel", b =>
                {
                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("MovieReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("MovieReadModelId");

                            b1.ToTable("Movies");

                            b1.WithOwner()
                                .HasForeignKey("MovieReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Partition.Application.Contracts.ReadModels.PartitionReadModel", b =>
                {
                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("PartitionReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("PartitionReadModelId");

                            b1.ToTable("Partitions");

                            b1.WithOwner()
                                .HasForeignKey("PartitionReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.AvailableSeatReadModel", b =>
                {
                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("AvailableSeatReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("AvailableSeatReadModelId");

                            b1.ToTable("AvailableSeats");

                            b1.WithOwner()
                                .HasForeignKey("AvailableSeatReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.ReservationReadModel", b =>
                {
                    b.OwnsMany("JordiAragonZaragoza.Cinema.Reservation.Auditorium.Application.Contracts.ReadModels.SeatReadModel", "Seats", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Row")
                                .HasColumnType("integer");

                            b1.Property<int>("SeatNumber")
                                .HasColumnType("integer");

                            b1.HasKey("Id", "ReservationId");

                            b1.HasIndex("ReservationId");

                            b1.ToTable("ReservationsSeats", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("ReservationReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("ReservationReadModelId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Showtime.Application.Contracts.ReadModels.ShowtimeReadModel", b =>
                {
                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("ShowtimeReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("ShowtimeReadModelId");

                            b1.ToTable("Showtimes");

                            b1.WithOwner()
                                .HasForeignKey("ShowtimeReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.Tenant.Application.Contracts.ReadModels.TenantReadModel", b =>
                {
                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("TenantReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("TenantReadModelId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.User.Application.Contracts.ReadModels.UserAuthorizationReadModel", b =>
                {
                    b.OwnsMany("JordiAragonZaragoza.Cinema.Reservation.User.Application.Contracts.ReadModels.PermissionReadModel", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserAuthorizationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PermissionValue");

                            b1.HasKey("Id", "UserAuthorizationId");

                            b1.HasIndex("UserAuthorizationId");

                            b1.ToTable("UserAuthorizationPermissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserAuthorizationId");
                        });

                    b.OwnsMany("JordiAragonZaragoza.Cinema.Reservation.User.Application.Contracts.ReadModels.RoleReadModel", "Roles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserAuthorizationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RoleValue");

                            b1.HasKey("Id", "UserAuthorizationId");

                            b1.HasIndex("UserAuthorizationId");

                            b1.ToTable("UserAuthorizationRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserAuthorizationId");
                        });

                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("UserAuthorizationReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("UserAuthorizationReadModelId");

                            b1.ToTable("UsersAuthorizations");

                            b1.WithOwner()
                                .HasForeignKey("UserAuthorizationReadModelId");
                        });

                    b.Navigation("Permissions");

                    b.Navigation("Roles");

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("JordiAragonZaragoza.Cinema.Reservation.User.Application.Contracts.ReadModels.UserReadModel", b =>
                {
                    b.OwnsOne("JordiAragonZaragoza.SharedKernel.Application.Contracts.Interfaces.ScopeInfo", "Scope", b1 =>
                        {
                            b1.Property<Guid>("UserReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DomainId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_DomainId");

                            b1.Property<Guid?>("PartitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_PartitionId");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("Scope_TenantId");

                            b1.HasKey("UserReadModelId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserReadModelId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
