<Project Sdk="Microsoft.NET.Sdk">
  
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>34c45fcd-59fa-4283-97a7-896bedf5b6ed</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Seq" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.KurrentDB" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.SharedKernel\JordiAragonZaragoza.Cinema.SharedKernel.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Api.Command\JordiAragonZaragoza.Cinema.Reservation.Api.Command.csproj" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Api.Query\JordiAragonZaragoza.Cinema.Reservation.Api.Query.csproj" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Mcp.Gateway\JordiAragonZaragoza.Cinema.Reservation.Mcp.Gateway.csproj" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Worker.ReadModelMigrator\JordiAragonZaragoza.Cinema.Reservation.Worker.ReadModelMigrator.csproj" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Worker.Seeder\JordiAragonZaragoza.Cinema.Reservation.Worker.Seeder.csproj" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Worker.Projector\JordiAragonZaragoza.Cinema.Reservation.Worker.Projector.csproj" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Worker.Reactor\JordiAragonZaragoza.Cinema.Reservation.Worker.Reactor.csproj" />
  </ItemGroup>

</Project>
