<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>0bad82f7-9ee6-4fdf-9c4c-e98b71e43d87</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>
  <ItemGroup Condition="'$(UseProjectReference)' == 'true'">
   <ProjectReference Include="..\..\..\JordiAragonZaragoza.SharedKernel\src\JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi\JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi.csproj" />
  </ItemGroup>	
  <ItemGroup Condition="'$(UseProjectReference)' == 'false'">
   <PackageReference Include="JordiAragonZaragoza.SharedKernel.Presentation.HttpRestfulApi" />
  </ItemGroup>	
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
  </ItemGroup>	
  <ItemGroup>
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation\JordiAragonZaragoza.Cinema.Reservation.csproj" />
    <ProjectReference Include="..\JordiAragonZaragoza.Cinema.Reservation.Api.Command.Contracts.V1\JordiAragonZaragoza.Cinema.Reservation.Api.Command.Contracts.V1.csproj" />
  </ItemGroup>
</Project>
