<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Ardalis.GuardClauses" />
		<PackageReference Include="Ardalis.HttpClientTestExtensions" />
		<PackageReference Include="Aspire.Hosting.Testing" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Respawn" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.msbuild">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\JordiAragonZaragoza.Cinema\JordiAragonZaragoza.Cinema.csproj" />
	  <ProjectReference Include="..\..\..\src\JordiAragonZaragoza.Cinema.Reservation.Api.Query.Contracts.V2\JordiAragonZaragoza.Cinema.Reservation.Api.Query.Contracts.V2.csproj" />
	</ItemGroup>
</Project>