<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Ardalis.HttpClientTestExtensions" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="Respawn" />
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="Testcontainers.KurrentDb" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.msbuild">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<None Update="xunit.runner.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
      <!-- TODO: Temporal. Remove it-->
	  <Compile Remove="Api.Command\Common\ApiCommandSharedTestCollection.cs" />
	  <Compile Remove="Api.Command\Common\BaseHttpRestfulApiFunctionalTests.cs" />
	  <Compile Remove="Api.Command\Common\CustomWebApplicationFactory.cs" />
	  <Compile Remove="Api.Command\Common\EndpointRouteHelpers.cs" />
	  <Compile Remove="Api.Command\Common\FunctionalTestsFixture.cs" />
	  <Compile Remove="Api.Command\Common\SeedData.cs" />
	  
	  <Compile Remove="Api.Command\V2\Showtime\CancelShowtimeTests.cs" />
	  <Compile Remove="Api.Command\V2\Showtime\PurchaseReservationTests.cs" />
	  <Compile Remove="Api.Command\V2\Showtime\ReserveSeatsTests.cs" />
	  <Compile Remove="Api.Command\V2\Showtime\ScheduleShowtimeTests.cs" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\JordiAragonZaragoza.Cinema.Reservation.Api.Command\JordiAragonZaragoza.Cinema.Reservation.Api.Command.csproj" />
	  <ProjectReference Include="..\..\..\src\JordiAragonZaragoza.Cinema.Reservation.Api.Query\JordiAragonZaragoza.Cinema.Reservation.Api.Query.csproj" />
	  <ProjectReference Include="..\..\TestUtilities\JordiAragonZaragoza.Cinema.Reservation.TestUtilities\JordiAragonZaragoza.Cinema.Reservation.TestUtilities.csproj" />
	</ItemGroup>
</Project>